### ISSUE TITLE
Implement MSAA

### ISSUE THREAD

**Issue by bjjones** [JiangYizhou/aquarium-test#11]
We should implement MSAA functionality soon. What is the blocking factor here? Is it lack of Vulkan/Dawn MSAA support?

**Comment by JiangYizhou** [comment]
I 've checked with Jiawei, MSAA of Vulkan and D3D12 in Dawn is implemented, and metal is going to be implemented soon.

**Comment by bjjones** [comment]
Yizhou - I'd like to get MSAA working as soon as possible for D3D12 testing. Do you mind if I work on this item?

**Comment by JiangYizhou** [comment]
@bjjones Sorry to block on your work, I'm working on other backend of Aquarium, so I only have half time on Aquarium dawn backend now. I 've rebased Aquarium to latest dawn commit today. Very appreciate it if you could help on this feature, and any refactors or comments are welcomed.

**Comment by bjjones** [comment]
Done.
