### ISSUE TITLE
Implement Debug/Release Builds

### ISSUE THREAD

**Issue by bjjones** [JiangYizhou/aquarium-test#21]
Currently Dawn is getting built as debug which causes backend debug validation layers to be enabled. We should be able to switch between release and debug builds.

Perhaps `out/debug` and `out/release` instead of a single `out/build`?

**Comment by Jiawei-Shao** [comment]
Hi Brandon, now you can specify "is_debug = false" in "gn args out/Release" to have a release build, just like what we can do for Dawn and Chromium.

**Comment by bjjones** [comment]
Ah, my mistake. I must have missed the update.
