### ISSUE TITLE
Share viewUniforms Globally

### ISSUE THREAD

**Issue by bjjones** [JiangYizhou/aquarium-test#6]
The function `updateGlobalUniforms()` generates the scene's common position values and are pushed to a individual models and then update every frame. Instead, we could eliminate many CPU->GPU copies by only updating these values on the GPU one time and then sharing between all models.

The models currently updating a separate copy of `viewUniforms` every frame are:
1. FishModel
2. GenericModel
3. InnerModel
4. OutsideModel
5. SeaweedModel

**Comment by JiangYizhou** [comment]
This issue is fixed!
