### ISSUE TITLE
Eliminate Unnecessary DrawIndexed Calls

### ISSUE THREAD

**Issue by bjjones** [JiangYizhou/aquarium-test#8]
Currently, `DrawIndexed()` is used to draw `InnerModel`, `OuterModel`, and one instance of `GenericModel` where drawn instances is 1 . There is an overhead associated with `DrawIndexed()` that is unnecessary and could be eliminated by using `Draw()` instead.

I also see an instance of `GenericModel` where drawn instances is 0. In this case, we should not draw at all.

**Comment by JiangYizhou** [comment]
@bjjones These two models should not rendered because they don't have world matrices, so I removed them in the above commit.
Both of the Draw and DrawIndexed functions passes instance param. DrawIndexed uses index buffer while Draw uses vertex buffer.
